### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by amree**

### CODE REVIEW

**Comment by amree** [comment]
@faizalzakaria TIL about `gemspec` vs `Gemfile`. I'm OK either way, but I think I'm leaning towards Gemfile more. I'm also thinking moving the `runtime_dependency` to Gemfile too. What do you think?

Thanks for the link, we'll definitely try reading each and every one of them.

**Comment by faizalzakaria** [comment]
@amree ,

if you move `runtime_dependency` to Gemfile, then this gem will only resolve the dependencies through bundler.

Which means , `gem install teecket` would lead to a missing dependencies error.

So its best for you to keep the runtime dependency on the Gemspec itself.

**Comment by amree** [comment]
That's true. I forgot about it after not touching that part for a long time.

**Comment by amree** [comment]
@faizalzakaria: Updated. Kindly review again when you have time

**Comment by faizalzakaria** [comment]
:+1:

**Pull request merged**
